### ISSUE TITLE
"Select Hash Function" dropdown should default to the last hash function used

### ISSUE THREAD

**Issue by MasterEric** [alexguirre/vscode-inline-hasher#3]
When hashing in multiple places, selecting a hash function that is not `joaat` is frustrating. You have to select it each time.

Proposal to add functionality such that the first highlighted option in the list is the last hash function used, such that simply pressing enter will use the last algorithm selected.

**Comment by alexguirre** [comment]
Thanks for the suggestion. Now the first option will be the last hash function used.
![](https://user-images.githubusercontent.com/12873137/103583531-26786f80-4ee0-11eb-9975-9467ed7318c5.png)

**Comment by EliteMasterEric** [comment]
@alexguirre Great work! 😊
